<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>5929dda4-4788-418e-ab0e-c04a0afab641</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.4.6" />
    <PackageReference Include="Aspire.Hosting.Keycloak" Version="13.4.6-preview.1.26319.6" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.4.6" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.NodeJS.Extensions" Version="9.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VideoCatalog.PublicApi\VideoCatalog.PublicApi.csproj" />
    <ProjectReference Include="..\VideoCatalog.AdminApi\VideoCatalog.AdminApi.csproj" />
    <ProjectReference Include="..\VideoCatalog.AdminPortal\VideoCatalog.AdminPortal.csproj" />
  </ItemGroup>

</Project>
